/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/categories`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/item/[id] copy`; params?: Router.UnknownInputParams; } | { pathname: `/books/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/category/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/contact/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/contact copy/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/delete/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/edit/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/screens/item/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/categories`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/item/[id] copy`; params?: Router.UnknownOutputParams; } | { pathname: `/books/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/category/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/contact/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/contact copy/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/delete/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/edit/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/screens/item/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/categories${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/screens/item/[id] copy${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/categories`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/item/[id] copy`; params?: Router.UnknownInputParams; } | `/books/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/category/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/contact/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/contact copy/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/delete/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/edit/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/screens/item/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/books/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/category/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/contact/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/contact copy/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/delete/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/edit/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/screens/item/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
